"use client";
import { useCallback, useEffect, useRef, useState } from "react";
import { meowoneApi, type GatewayLogsResponse } from "@/lib/meowone-api";
export default function GatewayLogsPage(){
  const [sessionId,setSessionId]=useState(""); const [limit,setLimit]=useState("50"); const cursorRef=useRef(0); const [cursorDisplay,setCursorDisplay]=useState(0); const [items,setItems]=useState<GatewayLogsResponse["items"]>([]); const [polling,setPolling]=useState(false); const [error,setError]=useState("");
  const load=useCallback(async()=>{try{setError(""); const res=await meowoneApi.queryGatewayLogs({session_id:sessionId.trim()||undefined,cursor:cursorRef.current,limit:limit?Number(limit):50}); setItems((prev)=>{const seen=new Set(prev.map((x)=>x.id)); const merged=[...prev]; for(const row of res.items){if(!seen.has(row.id)) merged.push(row);} return merged.sort((a,b)=>a.id-b.id);}); cursorRef.current=res.nextCursor; setCursorDisplay(res.nextCursor);}catch(e){setError((e as Error).message);}},[sessionId,limit]);
  useEffect(()=>{if(!polling)return; const id=window.setInterval(()=>void load(),2000); return ()=>window.clearInterval(id);},[polling,load]);
  return (<div className="space-y-4"><h1 className="text-title-md2 font-semibold text-dark dark:text-white">网关日志</h1><p className="text-sm text-body dark:text-dark-6">轮询 GET `/api/gateway/logs`，通过 cursor 增量拉取。</p><div className="flex flex-wrap gap-2"><input value={sessionId} onChange={(e)=>setSessionId(e.target.value)} placeholder="session_id（可选）" className="rounded-lg border border-stroke bg-white px-3 py-2 text-sm dark:border-dark-3 dark:bg-dark-2"/><input value={limit} onChange={(e)=>setLimit(e.target.value)} placeholder="条数" className="w-24 rounded-lg border border-stroke bg-white px-3 py-2 text-sm dark:border-dark-3 dark:bg-dark-2"/><button className="rounded-lg bg-primary px-4 py-2 text-sm text-white" onClick={()=>void load()}>拉取</button><button className={`rounded-lg border px-4 py-2 text-sm dark:border-dark-3 ${polling?"border-primary text-primary":"border-stroke"}`} onClick={()=>setPolling((p)=>!p)}>{polling?"停止轮询":"每 2s 轮询"}</button><button className="rounded-lg border border-stroke px-4 py-2 text-sm dark:border-dark-3" onClick={()=>{setItems([]);cursorRef.current=0;setCursorDisplay(0);}}>清空</button></div>{error?<p className="text-sm text-red">{error}</p>:null}<p className="text-xs text-body dark:text-dark-6">下一个游标: {cursorDisplay}</p><div className="max-h-[60vh] space-y-2 overflow-auto rounded-xl border border-stroke bg-white p-3 dark:border-dark-3 dark:bg-dark-2">{items.map((row)=><div key={row.id} className="rounded-lg bg-gray-1 p-2 text-xs dark:bg-dark"><div className="text-body dark:text-dark-6">#{row.id} · {row.event} · {row.sessionId}</div><pre className="mt-1 whitespace-pre-wrap break-all text-dark dark:text-white">{row.data}</pre></div>)}{!items.length?<p className="text-xs text-body dark:text-dark-6">暂无日志</p>:null}</div></div>);
}
