"use client";
import { useEffect, useState } from "react";
import { meowoneApi, type ModelsListResponse } from "@/lib/meowone-api";
export default function ModelsPage(){
  const [data,setData]=useState<ModelsListResponse|null>(null); const [error,setError]=useState("");
  const [name,setName]=useState(""); const [provider,setProvider]=useState("openai-compatible"); const [baseUrl,setBaseUrl]=useState(""); const [apiKey,setApiKey]=useState(""); const [enabled,setEnabled]=useState(true); const [isDefault,setIsDefault]=useState(false);
  const load=async()=>{try{setError("");setData(await meowoneApi.listModels());}catch(e){setError((e as Error).message);}};
  useEffect(()=>{void load();},[]);
  return (<div className="space-y-6"><h1 className="text-title-md2 font-semibold text-dark dark:text-white">模型管理</h1>{error?<p className="text-sm text-red">{error}</p>:null}<div className="rounded-xl border border-stroke bg-white p-4 dark:border-dark-3 dark:bg-dark-2"><h2 className="mb-3 text-sm font-semibold">新增 / 更新</h2><div className="grid grid-cols-1 gap-2 md:grid-cols-2"><input value={name} onChange={(e)=>setName(e.target.value)} placeholder="名称" className="rounded-lg border border-stroke px-3 py-2 text-sm dark:border-dark-3"/><input value={provider} onChange={(e)=>setProvider(e.target.value)} placeholder="提供方" className="rounded-lg border border-stroke px-3 py-2 text-sm dark:border-dark-3"/><input value={baseUrl} onChange={(e)=>setBaseUrl(e.target.value)} placeholder="基础地址" className="rounded-lg border border-stroke px-3 py-2 text-sm dark:border-dark-3 md:col-span-2"/><input value={apiKey} onChange={(e)=>setApiKey(e.target.value)} placeholder="api_key" className="rounded-lg border border-stroke px-3 py-2 text-sm dark:border-dark-3 md:col-span-2"/><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={enabled} onChange={(e)=>setEnabled(e.target.checked)}/>启用</label><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={isDefault} onChange={(e)=>setIsDefault(e.target.checked)}/>设为默认</label></div><button className="mt-3 rounded-lg bg-primary px-4 py-2 text-sm text-white" onClick={async()=>{await meowoneApi.upsertModel({name,provider,base_url:baseUrl,api_key:apiKey,enabled,is_default:isDefault,extra:{}});await load();}}>提交</button></div><div className="overflow-auto rounded-xl border border-stroke bg-white dark:border-dark-3 dark:bg-dark-2"><table className="w-full text-left text-sm"><thead className="border-b border-stroke bg-gray-1 dark:border-dark-3 dark:bg-dark"><tr><th className="p-3">名称</th><th className="p-3">提供方</th><th className="p-3">基础地址</th><th className="p-3">状态</th><th className="p-3">操作</th></tr></thead><tbody>{(data?.models||[]).map((m)=>{const n=String(m.name??"");return <tr key={n} className="border-b border-stroke dark:border-dark-3"><td className="p-3">{n}</td><td className="p-3">{String(m.provider??"")}</td><td className="max-w-xs truncate p-3">{String(m.base_url??"")}</td><td className="p-3 text-xs">默认:{String(m.is_default)} 启用:{String(m.enabled)}</td><td className="space-x-2 p-3"><button className="text-primary" onClick={async()=>{await meowoneApi.setDefaultModel(n);await load();}}>设默认</button><button className="text-red" onClick={async()=>{if(!confirm(`删除模型 ${n}?`))return;await meowoneApi.deleteModel(n);await load();}}>删除</button></td></tr>;})}</tbody></table></div></div>);
}
